package com.hyuk.side.enums;

public enum RegisterEnum {
    FAILURE,
    SUCCESS,
    FAILURE_EMAIL_DUPLICATE,
    FAILURE_EMAIL_NOT_VERIFIED,
    FAILURE_NICKNAME_DUPLICATE,
    FAILURE_CONTACT_DUPLICATE

}
